require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/create_doctors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CreateDoctor. As you add validations to CreateDoctor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CreateDoctor.create! valid_attributes
      get create_doctors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      create_doctor = CreateDoctor.create! valid_attributes
      get create_doctor_url(create_doctor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_create_doctor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      create_doctor = CreateDoctor.create! valid_attributes
      get edit_create_doctor_url(create_doctor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CreateDoctor" do
        expect {
          post create_doctors_url, params: { create_doctor: valid_attributes }
        }.to change(CreateDoctor, :count).by(1)
      end

      it "redirects to the created create_doctor" do
        post create_doctors_url, params: { create_doctor: valid_attributes }
        expect(response).to redirect_to(create_doctor_url(CreateDoctor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CreateDoctor" do
        expect {
          post create_doctors_url, params: { create_doctor: invalid_attributes }
        }.to change(CreateDoctor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post create_doctors_url, params: { create_doctor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested create_doctor" do
        create_doctor = CreateDoctor.create! valid_attributes
        patch create_doctor_url(create_doctor), params: { create_doctor: new_attributes }
        create_doctor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the create_doctor" do
        create_doctor = CreateDoctor.create! valid_attributes
        patch create_doctor_url(create_doctor), params: { create_doctor: new_attributes }
        create_doctor.reload
        expect(response).to redirect_to(create_doctor_url(create_doctor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        create_doctor = CreateDoctor.create! valid_attributes
        patch create_doctor_url(create_doctor), params: { create_doctor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested create_doctor" do
      create_doctor = CreateDoctor.create! valid_attributes
      expect {
        delete create_doctor_url(create_doctor)
      }.to change(CreateDoctor, :count).by(-1)
    end

    it "redirects to the create_doctors list" do
      create_doctor = CreateDoctor.create! valid_attributes
      delete create_doctor_url(create_doctor)
      expect(response).to redirect_to(create_doctors_url)
    end
  end
end
